<a href="https://colab.research.google.com/github/gleyce-alves/machine_learning_senac/blob/main/Aula03_atv_listas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercício 01

In [ ]:
palavras = ["codigo", "linguagem", "web"]

In [ ]:
numeros = [18, 123]

In [ ]:
vazia = []

In [ ]:
lista_mista = ["oi", 2.0, 5*2, [10,20]]

In [ ]:
print(numeros)

[18, 123]


In [ ]:
print(lista_mista)

['oi', 2.0, 10, [10, 20]]


In [ ]:
nova_lista = [numeros,palavras]

In [ ]:
print(nova_lista)

[[18, 123], ['codigo', 'linguagem', 'web']]


### Exercício 02

In [ ]:
uma_lista = ["oi", 2.0, 5, [10, 20]]

In [ ]:
print(len(uma_lista))

4


In [ ]:
print(len(['spam!', 1, ['bolo', 'bolacha', 'biscoito'], [1, 2, 3]]))

### Exercício 03

In [ ]:
numeros = [18, 424, 86, 13, 66, 8338, 74]

In [ ]:
print(numeros[2])

86


Printa o item da posição 02 da lista, correspondente ao valor 86.

In [ ]:
print(numeros[9-8])

424


Printa o item da posição 01 da lista, correspondente ao valor 424.

In [ ]:
print(numeros[-2])

8338


Printa o item da penúltima posição da lista, correspondente ao valor 8338.

In [ ]:
print(numeros[len(numeros)-1])

Printa o número correspondente a posição referente a quantidade de itens da lista - 1, ou seja, numeros[len(numeros)-1] = numeros[6] = 74.

### Exercício 04

In [ ]:
uma_lista = [3, 5, "Cibele", 3.14, False]

In [ ]:
print(len(uma_lista))

5


Printa o comprimento de *uma_lista*


### Exercício 05

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(len(uma_lista[5]))

Printa o quinto elemento da lista, nesse caso é 3.14.

### Exercício 06

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(uma_lista)

[3, 5, 'Cibele', [88, 99, 'Suely'], [], 3.14, False]


In [ ]:
print(uma_lista[5])

3.14


Printa o 5° elemento da lista, nesse caso é 3.14

### Exercício 07

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(uma_lista[2].upper())

Printa, em letras maiusculas, o que está na posição 02 da lista.

### Exercício 08

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(uma_lista[2][0])

### Exercício 09

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(3.14 in uma_lista)

Verifica se o número 3.14 está contido na lista *uma_lista*

### Exercício 10

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(88 in uma_lista)

Verifica se o número 88 está contido na lista uma_lista

### Exercício 11

In [ ]:
uma_lista = [1, 3, 5]

In [ ]:
outra_lista = [2, 4, 6]

In [ ]:
print(uma_lista + outra_lista)

[1, 3, 5, 2, 4, 6]


Faz a concatenação das duas listas, ou seja, a junção dos elementos das duas.

### Exercício 12

In [ ]:
uma_lista = [1, 3, 5]

In [ ]:
print(uma_lista * 3)

[1, 3, 5, 1, 3, 5, 1, 3, 5]


Vai printar a lista com seus elementos repetidos três vezes.

### Exercício 13

In [ ]:
uma_lista = [3, 5, "Cibele", [88, 99, "Suely"], [ ], 3.14, False]

In [ ]:
print(uma_lista[4:])

[[], 3.14, False]


Printa do elemento 04 em diante da lista.

### Exercício 14

In [ ]:
uma_lista = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
uma_lista[1:3] = ['x', 'y']

Substitui o elemento 01 da lista por **x** e o elemento dois da lista por y

In [ ]:
print(uma_lista)

['a', 'x', 'y', 'd', 'e', 'f']


### Exercício 15

In [ ]:
uma_lista = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
uma_lista[1:3] = []

Apaga os elementos correspondente ao índice 1 e 2 da lista.

In [ ]:
print(uma_lista)

['a', 'd', 'e', 'f']


### Exercício 16

In [ ]:
uma_lista = ['a', 'd', 'f']

In [ ]:
uma_lista[1:1] = ['b', 'c']

Vai adicionar os elementos **'b'** e **'c'** na lista a partir do índice 01

In [ ]:
print(uma_lista)

['a', 'b', 'c', 'b', 'c', 'd', 'f']


In [ ]:
uma_lista[4:4] = ['e']

Adciona a letra 'e' na posição 04 da lista.

In [ ]:
print(uma_lista)

['a', 'b', 'c', 'b', 'e', 'c', 'd', 'f']


### Exercício 17

In [ ]:
uma_lista = [4, 1, 8, 6, 3]

In [ ]:
uma_lista[2] = True

Substitui o elemento 02 da lista por *True*

In [ ]:
print(uma_lista)

[4, 1, True, 6, 3]


### Exercício 18

In [ ]:
a = ['um', 'dois', 'três']

In [ ]:
del a[1]

Apaga o o elemento da posição 01

In [ ]:
print(a)

['um', 'três']


In [ ]:
lista = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
del lista[1:5]

Apaga os elementos correspondente aos índice do 01 ao 04 da lista.

In [ ]:
print(lista)

['a', 'f']


### Exercício 19

In [ ]:
lista_a = [4, 1, 8, 6, 3]

In [ ]:
lista_b = lista_a

In [ ]:
lista_b[3] = 22

In [ ]:
print(lista_a)

[4, 1, 8, 22, 3]


### Exercício 20

In [ ]:
lista_original = [5, 6, 7, 8]

In [ ]:
print(lista_original*3)

[5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]


Printa a lista e repete os elementos três vezes.

### Exercício 21

In [ ]:
lista_original = [5, 6, 7, 8]

In [ ]:
print(lista_original*3)

[5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]


In [ ]:
lista_nova = [lista_original] * 3

In [ ]:
print(lista_nova)

[[5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8]]


Printa a lista 3 vezes, cada vez sendo também uma lista.

### Exercício 22

In [ ]:
lista_original = [5, 6, 7, 8]

In [ ]:
lista_nova = [lista_original] * 3

In [ ]:
print(lista_nova)

[[5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8]]


Printa a nova lista três vezes, cada elemento é *lista_original*


In [ ]:
lista_original[1] = 22

In [ ]:
print(lista_nova)

[[5, 22, 7, 8], [5, 22, 7, 8], [5, 22, 7, 8]]


### Exercício 23

In [ ]:
lista_a = [4, 1, 8, 6, 3]

In [ ]:
lista_b = lista_a * 2

A *lista_b* é duas vezes a variável *lista_a*

In [ ]:
lista_b[3] = 35

Substitui o elemento 03 da lista pelo elemento 35

In [ ]:
print(lista_a)

[4, 1, 8, 6, 3]


### Exercício 24

In [ ]:
lista_a = [4, 1, 8, 6, 3]

In [ ]:
lista_b = [lista_a] * 2

A variável *lista_b* é uma lista da *lista_a* duas vezes.

In [ ]:
lista_a[3] = 35

Substitui o elemento da posição 03 da lista pelo elemento 35.

In [ ]:
print(lista_b)

[[4, 1, 8, 35, 3], [4, 1, 8, 35, 3]]


Como definimos a *lista_b* dependente da *lista_a*, então a *lista_b* também é alterada.

### Exercício 25

In [ ]:
uma_lista = [4, 1, 8, 6, 3]

In [ ]:
uma_lista.append(True)

O método append, nesse caso, vai adicionar o elemento *True* ao final da lista.

In [ ]:
uma_lista.append(False)

O método append, nesse caso, vai adicionar  o elemento *False* ao final da lista.

In [ ]:
print(uma_lista)

[4, 1, 8, 6, 3, True, False]


### Exercício 26

In [ ]:
uma_lista = [4, 1, 8, 6, 3]

In [ ]:
uma_lista.insert(2,True)

O método insert, nesse caso, vai adicionar o elemento *True* no índice 02 da lista.

In [ ]:
uma_lista.insert(0,False)

O método insert, nesse caso, vai adicionar o elemento *True* no índice 0 da lista.

In [ ]:
print(uma_lista)

[False, False, 4, 1, True, 8, 6, 3]


### Exercício 27

In [ ]:
uma_lista = [4, 1, 8, 6, 3]

In [ ]:
temp = uma_lista.pop(2)

O método pop, nesse caso, retira o elemento da lista referente ao índice 02.

In [ ]:
temp = uma_lista.pop()

O método pop, nesse caso, retira o último elemento da lista.

In [ ]:
print(uma_lista)

[4, 1]


### Exerício 28

In [ ]:
uma_lista = [4, 1, 8, 6, 3]

In [ ]:
uma_lista = uma_lista.pop(0)

O método pop, nesse caso, vai retirar o elemento do índice 0. Posteriormente vai definir a variável *uma_lista* como esse elemento. No caso, a variável *uma_lista = 4*.

In [ ]:
print(uma_lista)

4
